version: "3.9"

services:

  codeql:
    image: tpf_codeql
    build:
      context: './SAST/sast/codeql'
      args:
        HOME: '/SAST'
      dockerfile: "./Dockerfile"
    volumes:
      - codeql:/codeql
    # Drop unnecessary Linux capabilities for security
    cap_drop:
      - ALL

  tp-framework-dev:
    image: tp-framework-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements-dev.txt"
      dockerfile: "./Dockerfile"
    env_file:
      - ./.env
    volumes:
      - codeql:/codeql
      - ./testability_patterns:/tp-framework/testability_patterns
      - ./out:/tp-framework/out
      - ./in:/tp-framework/in
      - ./tp_framework:/tp-framework/tp_framework
      - ./discovery:/tp-framework/discovery
      - ./qualitytests:/tp-framework/qualitytests
    entrypoint: bash
    # Drop unnecessary Linux capabilities for security
    cap_drop:
      - ALL

volumes:
  codeql: